services:
  backend:
    build: .
    container_name: media-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: media-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
